### ISSUE TITLE
Reverse Proxy: Frp -  expose a local server to the Internet

### ISSUE THREAD

**Issue by hhstore** [hhstore/blog#428]
# 📖 Abstract:

- ✅ 内网穿透(Frp) 使用教程.

# 💯 Related:

- ✅ #427 
- ✅ #36 
- ✅ xxx
- ✅ xxx

> 域名解析:

- ✅ #409 
- ✅ #333

**Comment by hhstore** [comment]
# 内网穿透方案:


- https://github.com/anderspitman/awesome-tunneling

## cpolar

- https://www.cpolar.com/
- 参考: https://youtu.be/Ym4d7uCo9eg?si=hENFwndW0qMtFlkx&t=1481

> 特点:

- 🌟🌟🌟🌟🌟
- 免费版: 4 个端口, 随机 `2 级域名`
- 易用性很高.
- 付费版, 年付, 很便宜. 是可以用的.
- 门槛低, 如果懒得自己`搭 FRP`, 很推荐这款.( FRP 遇到绑 `3 级域名` 问题, 无法解决)


## frp:

- https://github.com/fatedier/frp
- 🌟🌟🌟🌟🌟
- 首选自建方案, 免费+开源.
- 配置不算复杂. 小问题是: 不支持 `3 级域名`绑定. 只能 `2 级域名`. (只能裸 `IP + Port`)
- go 实现.

## rathole:

- https://github.com/rapiz1/rathole
- rust 实现, 性能更好, 但是据说稳定性有一定问题.


## cpolar

- https://www.cpolar.com/
- 参考: https://youtu.be/Ym4d7uCo9eg?si=hENFwndW0qMtFlkx&t=1481

## ngrok


- https://github.com/inconshreveable/ngrok
- 停止维护

**Comment by hhstore** [comment]
## Frp 配置教程:


- https://gofrp.org/zh-cn/

### 安装 frp:

> 下载:

- https://github.com/fatedier/frp/releases

> 安装脚本:


- https://github.com/mvscode/frps-onekey

```ruby

# 国内:
wget https://gitee.com/mvscode/frps-onekey/raw/master/install-frps.sh -O ./install-frps.sh
chmod 700 ./install-frps.sh
./install-frps.sh install


# 国外:
wget https://raw.githubusercontent.com/mvscode/frps-onekey/master/install-frps.sh -O ./install-frps.sh
chmod 700 ./install-frps.sh
./install-frps.sh install


```





### 内网 web 服务:

- https://gofrp.org/zh-cn/docs/examples/vhost-http/


```toml
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "web"
type = "http"
localPort = 80
customDomains = ["www.yourdomain.com"]

[[proxies]]
name = "web2"
type = "http"
localPort = 8080
customDomains = ["www.yourdomain2.com"]

```
