### ISSUE TITLE
Distributed Configuration Management Platform: 分布式配置中心方案

### ISSUE THREAD

**Issue by hhstore** [hhstore/blog#56]

**Comment by hhstore** [comment]
## 选择:


### etcd:

- CoreOS开源。
- 轻量级分布式key-value数据库，同时为集群环境的服务发现和注册而设计。
- 它提供了数据TTL失效（通过TTL更新来判断机器下线，来避免一定的网络分区问题）、数据改变监视、多值、目录监听、分布式锁原子操作等功能，来管理节点状态。


### disconf:
- https://github.com/knightliao/disconf
- 百度



## ref:

- http://vernonzheng.com/2015/02/09/%E5%BC%80%E6%BA%90%E5%88%86%E5%B8%83%E5%BC%8F%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E9%80%89%E5%9E%8B/

**Comment by hhstore** [comment]
## etcd + k8s:

- https://jimmysong.io/posts/kubernetes-etcd-ha-config/

**Comment by hhstore** [comment]
### python:

- https://juejin.im/entry/5b06786651882538ad3f0beb

- https://github.com/python-zk/kazoo

**Comment by hhstore** [comment]
## consul

### 安装 & 部署:

- https://github.com/hashicorp/consul/blob/master/demo/docker-compose-cluster/docker-compose.yml


```yaml
version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
consul-demo:
```
